# Generated by Django 4.2.11 on 2024-03-21 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now=True)),
                ('date_remove', models.DateTimeField(auto_now=True)),
                ('date_delivery', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.charts')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_passwords_change', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reading', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.users')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('COM', 'Community'), ('MFL', 'My_files'), ('BPS', 'Best_Practices')], max_length=3)),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('EXCEL', 'EXCEL'), ('PDF', 'PDF')], default='EXCEL', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.users')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.users')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.users')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.dashboards'),
        ),
        migrations.AddField(
            model_name='comments',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.files'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.users'),
        ),
        migrations.AddField(
            model_name='charts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.users'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('RDR', 'READER'), ('OWN', 'OWNER'), ('CMT', 'COMMENTATOR'), ('EDT', 'EDITOR')], max_length=20)),
                ('date_access_open', models.DateTimeField(auto_now=True)),
                ('date_access_close', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vard.users')),
            ],
        ),
    ]
