# Generated by Django 4.2.11 on 2024-03-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vard', '0002_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
