# Generated by Django 4.2.11 on 2024-04-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
